# Markdown Linting Configuration
# Comprehensive ruleset for maintaining high-quality Markdown files

# Spacing and Whitespace Rules
MD009: # Trailing spaces
  strict: true
  list_item_linebreak: false

MD010: # Hard tabs
  code_blocks: false

MD012: # Multiple consecutive blank lines
  maximum: 1

# Heading Rules
MD001: # Header levels should only increment by one level at a time
  enabled: true

MD002: # First header should be a top-level header
  level: 1

MD003: # Header style
  style: "atx"  # Prefer ATX-style headers (#)

MD018: # No space after hash on headers
  enabled: true

MD019: # Multiple spaces after header
  enabled: true

MD022: # Headers should be surrounded by blank lines
  enabled: true
  lines_above: 1
  lines_below: 1

# List Rules
MD004: # Unordered list style
  style: "consistent"

MD005: # Consistent indentation for list items
  enabled: true

MD006: # Consider starting bulleted lists at the beginning of the line
  enabled: true

MD007: # Unordered list indentation
  indent: 2
  start_indented: false

# Link and URL Rules
MD034: # Bare URL used
  enabled: true

MD039: # Spaces inside link or reference text
  enabled: true

# Code Block Rules
MD040: # Fenced code blocks should have a language specified
  enabled: true

MD046: # Code block style
  style: "fenced"

# Line Length Rules
MD013: # Line length
  line_length: 80
  strict: true
  stern: true
  code_blocks: false
  tables: false

# Miscellaneous Rules
MD036: # Emphasis used instead of a header
  enabled: true

MD037: # Spaces inside emphasis markers
  enabled: true

MD038: # Spaces inside code span elements
  enabled: true

MD041: # First line in a file should be a top-level header
  level: 1

MD042: # No empty links
  enabled: true

MD043: # Required headers
  enabled: false  # Can be customized if specific headers are required

MD044: # Proper names should have the correct capitalization
  enabled: false  # Can be customized with a list of proper nouns
  names: []

MD045: # Images should have alternate text
  enabled: true

MD047: # Files should end with a single newline character
  enabled: true

# Custom Configuration Options
default: true  # Enable all default rules
strict: true   # Enforce stricter checking

# Exceptions and Ignores
# Paths to ignore during linting
ignore:
  - 'node_modules/'
  - 'vendor/'
  - '*.min.md'

# Severity Levels
# You can adjust the severity of rules
# Levels: error, warning, suggestion
severity:
  MD009: error
  MD010: error
  MD013: warning  # Line length can be more flexible
  MD034: error
  MD040: error
  MD047: error

